# Generated by Django 4.2.1 on 2023-09-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(upload_to='skills_logo', verbose_name='Logo_Image'),
        ),
    ]
