# Generated by Django 4.2.1 on 2023-09-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_skill_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(upload_to='', verbose_name='Logo_Image'),
        ),
    ]
