# Generated by Django 4.2.1 on 2023-09-27 23:54

from django.db import migrations, models
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image1',
            field=models.ImageField(default=1, upload_to=resume.models.project_media_upload),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(default=1, upload_to=resume.models.project_media_upload),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.ImageField(default=1, upload_to=resume.models.project_media_upload),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image4',
            field=models.ImageField(default=1, upload_to=resume.models.project_media_upload),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(default=1, upload_to=resume.models.project_media_upload),
            preserve_default=False,
        ),
    ]
