# Generated by Django 4.2.1 on 2023-09-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.CharField(max_length=1000),
        ),
    ]
